import { GoogleGenAI } from "@google/genai";

export const runtime = "nodejs";

let aiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is missing.");
    }
    aiClient = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

const SYSTEM_INSTRUCTION = `You are Sumit Tuition App's AI Assistant, an expert educational administrator and data analyst for a tuition center / coaching academy.
Your task is to analyze student, class, attendance, fee, test, homework, and syllabus structured JSON data and generate clear, professional, actionable, and encouraging reports in clean Markdown format.

RULES:
1. Format output cleanly in beautiful, well-structured Markdown with appropriate headings (##, ###), bullet points, bold highlights, and tables where helpful.
2. Provide specific, data-backed insights based on the provided JSON data.
3. Keep tone professional, empathetic, constructive, and action-oriented.
4. Highlight risks clearly (e.g. attendance < 75%, unpaid fees, declining test marks) and offer practical remediation strategies.
5. NEVER suggest or imply automatic modification of database records. All suggestions are for human review.
6. When writing parent communications, use polite, clear, and professional language with appropriate placeholders if needed.`;

export default async function handler(req: any, res: any) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
  if (req.method === "OPTIONS") return res.status(204).end();
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed. Use POST." });

  try {
    let body = req.body;
    if (typeof body === "string") {
      try { body = JSON.parse(body); } catch {}
    }
    const { reportType, dataPayload, promptExtra } = body || {};

    if (!dataPayload) {
      return res.status(400).json({ error: "Missing dataPayload in request body" });
    }

    const ai = getGeminiClient();

    let userPrompt = `Analysis Request Type: ${reportType}\n\n`;
    userPrompt += `Provided Institution / Student Structured JSON Data:\n\`\`\`json\n${JSON.stringify(dataPayload, null, 2)}\n\`\`\`\n\n`;

    if (promptExtra) {
      userPrompt += `Additional Instructions / Focus Area:\n${promptExtra}\n\n`;
    }

    userPrompt += `Please generate the requested ${reportType} report in clean, well-formatted Markdown following the system guidance.`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: userPrompt,
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        temperature: 0.4,
      },
    });

    return res.status(200).json({
      success: true,
      markdown: response.text || "No response generated by AI.",
      timestamp: new Date().toISOString(),
    });
  } catch (err: any) {
    console.error("Error generating AI report:", err);
    return res.status(500).json({
      error: err.message || "Failed to generate AI report.",
    });
  }
}
